---
title: "Problem 52"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Permuted multiples

It can be seen that the number, $125874$, and its double, $251748$, contain exactly the same digits, but in a different order.

Find the smallest positive integer, $x$, such that $2x, 3x, 4x, 5x$, and $6x$, contain the same digits.

OEIS Sequence: [A133220](https://oeis.org/A133220)

## Solution
```{r}
library(microbenchmark)
```
```{r}
compute <- function(n) {
    i <- 1
    while (TRUE) {
        for (j in seq(10 ^ i, 10 ^ (i + 1) %/% n - 1)) {
            j_digits <- sort(utf8ToInt(as.character(j)))
            is_permuted <- TRUE
            for (k in 2:n) {
                k_digits <- sort(utf8ToInt(as.character(j * k)))
                if (any(j_digits != k_digits)) {
                    is_permuted <- FALSE
                    break
                }
            }
            if (is_permuted) return(j)
        }
        i <- i + 1
    }
}
```
```{r}
compute(2)
```
```{r}
compute(6)
```
```{r}
microbenchmark(compute(6))
```
