---
title: "Problem 46"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Goldbach's other conjecture

It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.

$$9 = 7 + 2 \times 1^2$$

$$15 = 7 + 2 \times 2^2$$

$$21 = 3 + 2 \times 3^2$$

$$25 = 7 + 2 \times 3^2$$

$$27 = 19 + 2 \times 2^2$$

$$33 = 31 + 2 \times 1^2$$

It turns out that the conjecture was false.

What is the smallest odd composite that cannot be written as the sum of a prime and twice a square?

OEIS Sequence: [A060003](https://oeis.org/A060003)

## Solution
```{r}
library(microbenchmark)
setwd("../../")
source("euler/R/calculus.R")
source("euler/R/primes.R")
```
```{r}
compute <- function() {
    sieve <- prime_sieve(6000)
    primes <- which(sieve)
    i <- 9
    while (TRUE) {
        if (!sieve[i]) {
            j <- 1
            is.not_expressible <- TRUE
            while (primes[j] < i) {
                if (is.square((i - primes[j]) / 2)) {
                    is.not_expressible <- FALSE
                    break
                }
                j <- j + 1
            }
            if (is.not_expressible) return(i)
        }
        i <- i + 2
    }
}
```
```{r}
compute()
```
```{r}
microbenchmark(compute())
```
