---
title: "Problem 81"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Path sum: two ways

In the $5$ by $5$ matrix below, the minimal path sum from the top left to the bottom right, by only moving to the right and down, is indicated in bold red and is equal to $2427$.

$$\begin{pmatrix} \boldsymbol{131} & 673 & 234 & 103 & 18 \\ \boldsymbol{201} & \boldsymbol{96} & \boldsymbol{342} & 965 & 150 \\ 630 & 803 & \boldsymbol{746} & \boldsymbol{422} & 111 \\ 537 & 699 & 497 & \boldsymbol{121} & 956 \\ 805 & 732 & 524 & \boldsymbol{37} & \boldsymbol{331} \end{pmatrix}$$

Find the minimal path sum from the top left to the bottom right by only moving right and down in [matrix.txt](https://projecteuler.net/project/resources/p081_matrix.txt) (right click and "Save Link/Target As..."), a 31K text file containing an $80$ by $80$ matrix.

## Solution
```{r}
library(microbenchmark)
```

```{r}
compute <- function(grid) {
    edge <- nrow(grid)
    for (i in (edge - 1):1) {
        grid[edge, i] <- grid[edge, i] + grid[edge, i + 1]
        grid[i, edge] <- grid[i, edge] + grid[i + 1, edge]
    }
    for (i in (edge - 1):1) {
        for (j in (edge - 1):1) {
            grid[i, j] <- grid[i, j] + min(grid[i + 1, j], grid[i, j + 1])
        }
    }
    return(grid[1, 1])
}
```
```{r}
grid_matrix <- matrix(c(c(131, 673, 234, 103, 18),
                        c(201, 96, 342, 965, 150),
                        c(630, 803, 746, 422, 111),
                        c(537, 699, 497, 121, 956),
                        c(805, 732, 524, 37, 331)),
                      nrow = 5, byrow = TRUE)

path <- "p081_matrix.txt"
```

```{r}
compute(grid_matrix)
```
```{r}
compute(matrix(as.integer(unlist(strsplit(readLines(path, warn = FALSE), ","))), nrow = 80, byrow = TRUE))
```

```{r}
microbenchmark(compute(matrix(as.integer(unlist(strsplit(readLines(path, warn = FALSE), ","))), nrow = 80, byrow = TRUE)))
```