---
title: "Problem 34"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Digit factorials

$145$ is a curious number, as $1! + 4! + 5! = 1 + 24 + 120 = 145$.

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: As $1! = 1$ and $2! = 2$ are not sums they are not included.

OEIS Sequence: [A014080](https://oeis.org/A014080)

## Solution
As $7 \times 9!$ have less than $8$ digit, then all numbers must be less then $10$ millions.
```{r}
library(arrangements)
library(microbenchmark)
```
```{r}
compute <- function() {
    result <- 0
    factorials <- factorial(0:9)
    for (i in 2:7) {
        combs <- combinations(0:9, i, replace = TRUE)
        for (j in seq_len(nrow(combs))) {
            candidate <- 0
            for (k in seq_len(i)) {
                candidate <- candidate + factorials[combs[j, k] + 1]
            }
            candidate_digits <- sort(as.integer(strsplit(as.character(candidate), NULL)[[1]]))
            if (length(candidate_digits) == i) {
                if (sum(candidate_digits == sort(combs[j,])) == i) {
                    result <- result + candidate
                }
            }
        }
    }
    return(result)
}
```
```{r}
compute()
```
```{r}
microbenchmark(compute())
```
