---
title: "Problem 40"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Champernowne's constant

An irrational decimal fraction is created by concatenating the positive integers:

$$0.123456789101112131415161718192021...$$

It can be seen that the $12^{th}$ digit of the fractional part is $1$.

If $d_n$ represents the $n^{th}$ digit of the fractional part, find the value of the following expression.

$$d_1 \times d_{10} \times d_{100} \times d_{1000} \times d_{10000} \times d_{100000} \times d_{1000000}$$

## Solution
```{r}
library(microbenchmark)
```
```{r}
compute <- function(d) {
    digits_number <- function(k) {
        return((10 ^ k * (9 * k - 1) + 1) %/% 9)
    }
    get_digit <- function(n) {
        k <- 0
        while (digits_number(k + 1) < n) {
            k <- k + 1
        }
        k <- k + 1
        rem <- n - digits_number(k - 1)
        num <- 10 ^ (k - 1) + rem %/% k - 1
        if (rem %% k == 0) {
            return(tail(as.integer(strsplit(as.character(num), NULL)[[1]]), 1))
        } else {
            return(as.integer(strsplit(as.character(num + 1), NULL)[[1]])[rem %% k])
        }
    }
    result <- 1
    for (i in 0:d) {
        result <- result * get_digit(10 ^ i)
    }
    return(result)
}
```
```{r}
compute(6)
```
```{r}
microbenchmark(compute(6))
```
