---
title: "Problem 31"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Coin sums

In the United Kingdom the currency is made up of pound (£) and pence (p). There are eight coins in general circulation:

$1p, 2p, 5p, 10p, 20p, 50p, £1 (100p),$ and $£2 (200p)$.

It is possible to make £$2$ in the following way:

$1 \times £1 + 1 \times 50p + 2 \times 20p + 1 \times 5p + 1 \times 2p + 3 \times 1p$

How many different ways can £$2$ be made using any number of coins?

## Solution
```{r}
library(microbenchmark)
```
```{r}
compute <- function(coins, n) {
    combinations <- c(1, rep(0, n))
    for (i in seq_along(coins)) {
        for (j in (coins[i] + 1):(n + 1)) {
            combinations[j] <- combinations[j] + combinations[j - coins[i]]
        }
    }
    return(tail(combinations, 1))
}
```
```{r}
coin_list <- c(1, 2, 5, 10, 20, 50, 100, 200)
```
```{r}
compute(coin_list, 200)
```
```{r}
microbenchmark(compute(coin_list, 200))
```
