---
title: "Problem #"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
theme: readable
---


```{r, message = FALSE}
library(microbenchmark)
library(bit64)
```

```{r}
compute <- function(n) {
    is.s_number <- function(a, b) {
        if (a > b) {
            return(FALSE)
        } else if (a == b) {
            return(TRUE)
        }
        modulo <- 10
        while (modulo < b) {
            quotient <- b %/% modulo
            remainder <- b %% modulo
            if (remainder < a & is.s_number(a - remainder, quotient)) {
                return(TRUE)
            }
            modulo <- modulo * 10
        }
        return(FALSE)
    }
    result <- 0
    for (i in 2:n) {
        number <- as.integer64(i)
        if (is.s_number(number, number * number)) {
            result <- result + number * number
        }
    }
    return(result)
}
```

```{r}
compute(10 ^ 2)
```
```{r}
compute(10 ^ 6)
```

```{r}
microbenchmark(compute(10 ^ 6), times = 1)
```