---
title: "Problem 36"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Double-base palindromes

The decimal number, $585 = 1001001001_2$ (binary), is palindromic in both bases.

Find the sum of all numbers, less than one million, which are palindromic in base $10$ and base $2$.

(Please note that the palindromic number, in either base, may not include leading zeros.)

## Solution
```{r}
library(microbenchmark)
```
```{r}
compute <- function(n) {
    result <- 0
    for (i in seq_len(log10(n))) {
        for (j in (10 ^ ceiling(i / 2 - 1)):(10 ^ ceiling(i / 2) - 1)) {
            palindrome <- as.integer(paste0(j, paste0(rev(strsplit(as.character(j), NULL)[[1]][0:(i %/% 2)]), collapse = ""), collapse = ""))
            binary <- trimws(paste0(as.integer(rev(intToBits(palindrome))), collapse = ""), "left", "0")
            if (binary == intToUtf8(rev(utf8ToInt(binary)))) {
                result <- result + palindrome
            }
        }
    }
    return(result)
}
```
```{r}
compute(1000000)
```
```{r}
microbenchmark(compute(1000000))
```
