---
title: "Problem 56"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Powerful digit sum

A googol ($10^{100}$) is a massive number: one followed by one-hundred zeros; $100^{100}$ is almost unimaginably large: one followed by two-hundred zeros. Despite their size, the sum of the digits in each number is only $1$.

Considering natural numbers of the form, $a^b$, where $a, b < 100$, what is the maximum digital sum?

OEIS Sequence: [A001597](https://oeis.org/A306481)

## Solution
```{r}
library(microbenchmark)
setwd("../../")
source("euler/R/big_int.R")
source("euler/R/math.R")
source("euler/R/numbers.R")
```
```{r}
compute <- function(n) {
    result <- 0
    for (a in (n - 5):(n - 1)) {
        number <- as.bigint(a)
        for (b in seq_len(n - 1)) {
            number %*=% a
            result <- fast_max(result, digits_sum(number))
        }
    }
    return(result)
}
```
```{r}
compute(100)
```
```{r}
microbenchmark(compute(100))
```