---
title: "Problem 29"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Distinct powers

Consider all integer combinations of ab for $2 ≤ a ≤ 5$ and $2 ≤ b ≤ 5$:

$$2^2 = 4, 2^3 = 8, 2^4 = 16, 2^5 = 32$$

$$3^2 = 9, 3^3 = 27, 3^4 = 81, 3^5 = 243$$

$$4^2 = 16, 4^3 = 64, 4^4 = 256, 4^5 = 1024$$

$$5^2 = 25, 5^3 = 125, 5^4 = 625, 5^5 = 3125$$

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

$$4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125$$

How many distinct terms are in the sequence generated by ab for $2 ≤ a ≤ 100$ and $2 ≤ b ≤ 100$?

OEIS Sequence: [A001597](https://oeis.org/A200975)

## Solution
```{r}
library(microbenchmark)
```
```{r}
compute <- function(n) {
    limit_powers <- as.integer(log2(n)); limit_numbers <- as.integer(sqrt(n))
    power_counts <- rep(0, limit_powers)
    for (i in 2:limit_numbers) {
        p <- as.integer(log(n, i))
        power_counts[p] <- power_counts[p] + 1
        j <- i * i
        while (j < limit_numbers) {
            ix <- as.integer(log(n, j))
            power_counts[ix] <- power_counts[ix] - 1
            j <- j * i
        }
        sieve <- rep(FALSE, limit_powers * n)
        duplicate_counts <- rep(0, limit_powers)
        count <- 0
        for (i in seq_len(limit_powers)) {
            for (j in 2:n) if (sieve[i * j])  count <- count + 1 else sieve[i * j] <- TRUE
            duplicate_counts[i] <- count
        }
    }
    return((n - 1) ^ 2 - sum(power_counts * duplicate_counts))
}
```
```{r}
compute(5)
```
```{r}
compute(100)
```
```{r}
microbenchmark(compute(100))
```