---
title: "Problem 357"
author: "Dynortice"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: readable
---
## Prime generating integers

Consider the divisors of $30$: $1$, $2$, $3$, $5$, $6$, $10$, $15$, $30$. It can be seen that for every divisor $d$ of $30$, $d + \frac{30}{d}$ is prime.

Find the sum of all positive integers $n$ not exceeding $100000000$ such that for every divisor $d$ of $n$, $d + \frac{n}{d}$ is prime.

OEIS Sequence: [A080715](https://oeis.org/A080715)

# Solution
```{r}
library(microbenchmark)
setwd("../../")
source("euler/R/primes.R")
options(scipen = 20)
```

```{r}
compute <- function(n) {
    sieve <- get_primality(n)
    candidates <- which(sieve)
    candidates <- candidates[(candidates - 1) %% 4 != 0] - 1
    result <- 0
    for (candidate in candidates) {
        if (!sieve[candidate %/% 2 + 2]) {
            next
        }
        is.valid <- TRUE
        for (i in 3:as.integer(sqrt(n) + 1)) {
            if (candidate %% i != 0) {
                next
            } else if (!sieve[candidate %/% i + i]) {
                is.valid <- FALSE
                break
            }
        }
        if (is.valid) {
            result <- result + candidate
        }
    }
    return(result)
}
```

```{r}
compute(100000000)
```

```{r}
microbenchmark(compute(100000000), times = 10)
```